PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/portfolio/urls.py
from django.urls import path
from .views import (ProjectListView,
                    ProjectCreateView,
                    ProjectUpdateView,
                    ProjectDeleteView,
                    ProjectDetailView,
                    ProjectImagesListView,
                    ProjectImagesCreateView,
                    ProjectImagesDeleteView)


urlpatterns = [
    path('', ProjectListView.as_view(), name='portfolio'),
    path('add/', ProjectCreateView.as_view(), name='portfolio_project_add'),
    path('<slug:slug>/', ProjectDetailView.as_view(), name='portfolio_project_view'),
    path('<slug:slug>/update/', ProjectUpdateView.as_view(), name='portfolio_project_update'),
    path('<slug:slug>/delete/', ProjectDeleteView.as_view(), name='portfolio_project_delete'),
    path('<slug:slug>/images/', ProjectImagesListView.as_view(), name='portfolio_project_images_view'),
    path('<slug:slug>/images/add/', ProjectImagesCreateView.as_view(), name='portfolio_project_images_add'),
    path('<slug:slug>/images/<int:pk>/delete/', ProjectImagesDeleteView.as_view(), name='portfolio_project_images_delete')
]

PHPStorm/teamvisionary-website/visionary_web/visionary_web/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
# from django.views.generic.base import RedirectView

from .sitemaps import StaticSitemap, PortfolioProjectSitemap


sitemaps = {
    'pages': StaticSitemap,
    'projects': PortfolioProjectSitemap,
}


urlpatterns = [
    path('', include('visionary_web.apps.pages.urls')),
    # path('dashboard/', TemplateView.as_view(template_name="dashboard/dashboard.html"), name='dashboard'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    # path('account/change_password/', TemplateView.as_view(template_name="accounts/change_password.html")),
    # path('account/forgot_password/', TemplateView.as_view(template_name="accounts/forgot_password.html")),
    # path('account/profile/', TemplateView.as_view(template_name="shop/account_profile.html")),
    # path('account/profile/edit/', TemplateView.as_view(template_name="shop/account_profile_edit.html")),
    # path('account/orders/', TemplateView.as_view(template_name="profiles/orders.html")),
    # path('account/offers/', TemplateView.as_view(template_name="profiles/offers.html")),
    # path('account/offers/edit/', TemplateView.as_view(template_name="shop/account_offers_edit.html")),
    # path('login/', TemplateView.as_view(template_name="accounts/login.html"), name='login'),
    # path('signup/', TemplateView.as_view(template_name="accounts/signup.html"), name='signup'),
    # TODO: CHECK THIS AND FIX IT
    # path('team/', TemplateView.as_view(template_name="pages/team.html"), name='team'),
    path('portfolio/', include('visionary_web.apps.portfolio.urls')),
    path('404/', TemplateView.as_view(template_name="pages/404.html"), name='404'),
    path('500/', TemplateView.as_view(template_name="pages/500.html"), name='500'),
    path('account/', include('visionary_web.apps.profiles.urls')),
    path('marketplace/', include('visionary_web.apps.marketplace.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    path('google68765b21417bb6ac.html', TemplateView.as_view(template_name="google68765b21417bb6ac.html", content_type="text/plain"), name="google_site_verification"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="sitemap"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/portfolio/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify


class Project(models.Model):
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, blank=True)
    short_description = models.CharField(max_length=200)
    description = models.TextField()
    project_download = models.URLField(blank=True)
    sketchfab = models.URLField(blank=True)
    youtube_video = models.URLField(blank=True)
    thumbnail = models.ImageField(upload_to="portfolio/")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/portfolio/%s/" % self.slug

    class Meta:
        permissions = (
            ("manage_projects", "Can manage the portfolio projects"),
        )
        unique_together = ("author", "title")


@receiver(pre_save, sender=Project)
def pre_save_product(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title + '-' + instance.author)


class ImageModel(models.Model):
    project = models.ForeignKey(Project, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="portfolio/")

PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/portfolio/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    thumbnail = forms.ImageField(widget=forms.FileInput)

    def __init__(self, *args, **kwargs):
        if 'thumbnail_required' in kwargs:
            self.thumbnail_required = kwargs.pop('thumbnail_required')
        else:
            self.thumbnail_required = True
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['thumbnail'].required = self.thumbnail_required

    class Meta:
        model = Project
        fields = ['title', 'author', 'short_description', 'description', 'project_download', 'sketchfab', 'thumbnail']

PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/portfolio/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

from .models import Project, ImageModel
from .forms import ProjectForm


class ProjectListView(ListView):
    template_name = 'portfolio/project_list.html'
    model = Project


class ProjectDetailView(DetailView):
    template_name = 'portfolio/project_single.html'
    model = Project


class ProjectCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'portfolio/project_forms.html'
    form_class = ProjectForm
    permission_required = 'portfolio.manage_projects'
    success_url = '/portfolio/'
    success_message = 'Project was created successfully!'


class ProjectUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'portfolio/project_forms.html'
    model = Project
    form_class = ProjectForm
    permission_required = 'portfolio.manage_projects'
    success_url = '/portfolio/'
    success_message = "Project was updated successfully!"

    def get_form_kwargs(self):
        kwargs = super(ProjectUpdateView, self).get_form_kwargs()
        kwargs.update({'thumbnail_required': False})
        return kwargs


class ProjectDeleteView(PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'portfolio/project_delete.html'
    model = Project
    success_url = '/portfolio/'
    success_message = "Project was deleted successfully!"
    permission_required = 'portfolio.manage_projects'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ProjectDeleteView, self).delete(request, *args, **kwargs)


class ProjectSlugMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project_slug"] = self.kwargs['slug']
        return context


class ProjectImagesSuccessUrlMixin:
    def get_success_url(self):
        slug = self.kwargs['slug']
        return reverse_lazy('portfolio_project_images_view', kwargs={'slug': slug})


class ProjectImagesListView(PermissionRequiredMixin, ProjectSlugMixin, ListView):
    template_name = 'portfolio/project_images_view.html'
    model = ImageModel
    permission_required = 'portfolio.manage_projects'

    def get_queryset(self):
        slug = self.kwargs['slug']
        try:
            qs = ImageModel.objects.filter(project__slug=slug)
            return qs
        except ImageModel.DoesNotExist:
            return ImageModel.objects.none()


class ProjectImagesCreateView(PermissionRequiredMixin, SuccessMessageMixin, ProjectSlugMixin, ProjectImagesSuccessUrlMixin, CreateView):
    template_name = 'portfolio/project_images_add.html'
    model = ImageModel
    fields = ['image']
    permission_required = 'portfolio.manage_projects'
    success_message = 'Image was added to the Project successfully!'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.project = Project.objects.get(slug=self.kwargs['slug'])
        self.object.save()
        return super().form_valid(form)


class ProjectImagesDeleteView(PermissionRequiredMixin, SuccessMessageMixin, ProjectSlugMixin, ProjectImagesSuccessUrlMixin, DeleteView):
    template_name = 'portfolio/project_images_delete.html'
    model = ImageModel
    success_message = "Image was removed successfully!"
    permission_required = 'portfolio.manage_projects'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ProjectImagesDeleteView, self).delete(request, *args, **kwargs)

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_delete.html
{% extends "pages/base/template.html" %}

{% block content %}

  <div class="section"></div>

  <div class="newcontainer">

    <div class="section row">

      <div class="col xl8 offset-xl2 s12">
        <div class="card-panel" style="padding: 25px 80px 25px 80px;">
        
        <center>
          <h5>Are you sure you want to delete this project?</h5>
          <br />

          <div class='row' style="margin-bottom: 0px;">
            <div class="col xl4 s12" style="margin-bottom: 15px;">
              <a href="/portfolio/" class='col s12 btn btn-large waves-effect purple darken-4'>Cancel</a>
            </div>
            <div class="col xl8 s12">
              <form method="post">{% csrf_token %}
                <button type="submit" class='col s12 btn btn-large waves-effect purple darken-1'>Confirm</button>
              </form>
              
            </div>
          </div>

        </center>
        
      
        </div>

      </div>
        
    </div>

  </div>


{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_forms.html
{% extends "pages/base/template.html" %}

{% load static %}
{% load widget_tweaks %}

{% block content %}

  <div class="section"></div>

  <div class="newcontainer">

    <div class="section row">

      <div class="col xl8 offset-xl2 s12">
        <div class="card-panel" style="padding: 25px 80px 25px 80px;">

          <form enctype="multipart/form-data" method="post">

            {% csrf_token %}
            <div class="section"></div>

            {{ form.non_field_errors }}

            <div class='row'>
              <div class='input-field col s12'>
                {{ form.title }}
                <label for='{{ form.title.id_for_label }}'>{{ form.title.label }}</label>
              </div>
              {% for error in form.title.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                {{ form.author }}
                <label for='{{ form.author.id_for_label }}'>{{ form.author.label }}</label>
              </div>
              {% for error in form.author.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                {{ form.short_description|add_class:"materialize-textarea" }}
                <label for='{{ form.short_description.id_for_label }}'>{{ form.short_description.label }}</label>
              </div>
              {% for error in form.short_description.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                {{ form.description|add_class:"materialize-textarea" }}
                <label for='{{ form.description.id_for_label }}'>{{ form.description.label }}</label>
              </div>
              {% for error in form.description.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                {{ form.planet_minecraft }}
                <label for='{{ form.planet_minecraft.id_for_label }}'>{{ form.planet_minecraft.label }}</label>
              </div>
              {% for error in form.planet_minecraft.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                {{ form.sketchfab }}
                <label for='{{ form.sketchfab.id_for_label }}'>{{ form.sketchfab.label }}</label>
              </div>
              {% for error in form.sketchfab.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <div class='file-field input-field col s12'>
                <div class="btn purple">
                  <span>Select Thumbnail</span>
                  <input type="file" name="thumbnail" id="id_thumbnail">
                </div>
                <div class="file-path-wrapper">
                  <input type="text" class="file-path" placeholder="{% if form.thumbnail.value %}{{ form.thumbnail.value }}{% else %}Choose a file{% endif %}">
                </div>
              </div>
              
              {% for error in form.thumbnail.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <br />
            <center>
              <div class='row'>
                <a href="/portfolio/" name='btn_login' class='col s3 btn btn-large waves-effect grey darken-1'>Cancel</a>
                <button type='submit' name='btn_login' class='col s8 offset-s1 btn btn-large waves-effect purple darken-1'>Submit</button>
              </div>
            </center>
          </form>

        </div>

      </div>
        
    </div>

  </div>



{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_images_add.html
{% extends "pages/base/template.html" %}

{% block content %}

  <div class="section"></div>

  <div class="newcontainer">

    <div class="section row">

      <div class="col xl8 offset-xl2 s12">
        <div class="card-panel" style="padding: 25px 80px 25px 80px;">

          <form enctype="multipart/form-data" method="post">
          
            {% csrf_token %}

            {{ form.non_field_errors }}

            <div class='row'>
              <div class='file-field input-field col s12'>
                <div class="btn purple">
                  <span>Select Image</span>
                  <input type="file" name="image" required id="id_image">
                </div>
                <div class="file-path-wrapper">
                  <input type="text" class="file-path" placeholder="{% if form.image.value %}{{ form.image.value }}{% else %}Choose a file{% endif %}">
                </div>
              </div>
              
              {% for error in form.image.errors %}
                <span class="left red-text" >* {{ error }}</span>
              {% endfor %}
            </div>

            <div class='row'>
              <a href="{% url 'portfolio_project_images_view' slug=project_slug %}" name='btn_login' class='col s3 btn btn-large waves-effect grey darken-1'>Cancel</a>
              <button type='submit' name='btn_login' class='col s8 offset-s1 btn btn-large waves-effect purple darken-1'>Submit Image</button>
            </div>

          </form>

        </div>
      </div>
        
    </div>

  </div>

{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_images_delete.html
{% extends "pages/base/template.html" %}

{% load static %}
{% load widget_tweaks %}

{% block content %}

  <div class="section"></div>

  <div class="newcontainer">

    <div class="section row">

      <div class="col xl8 offset-xl2 s12">
        <div class="card-panel" style="padding: 25px 80px 25px 80px;">
        
        <center>
          
          <h5>Are you sure you want to delete the image?</h5>
          <br />

          <div class='row' style="margin-bottom: 0px;">
            <div class="col xl4 s12" style="margin-bottom: 15px;">
              <a href="{% url 'portfolio_project_images_view' slug=project_slug %}" class='col s12 btn btn-large waves-effect purple darken-4'>Cancel</a>
            </div>
            <div class="col xl8 s12">
              <form method="post">
                {% csrf_token %}
                <button type="submit" class='col s12 btn btn-large waves-effect purple darken-1'>Confirm</button>
              </form>
            </div>
          </div>

        </center>
        
      
        </div>

      </div>
        
    </div>

  </div>



{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_images_view.html
{% extends "pages/base/template.html" %}

{% block content %}

  <div class="newcontainer">

    <div class="section row">

      <div class="col xl8 offset-xl2 s12">
        <div class="card-panel" style="padding: 25px 80px 25px 80px;">
          <div class="row">

          {% if object_list.count > 0 %}
            
            <h5>List of images:</h5>
          
              {% for image in object_list %}
              <div class="col m6">
                <div class="card">
                  <div class="card-image">
                    <img src="{{image.image.url}}" width="350">
                  </div>
                  <div class="card-action">
                    <a href="{% url 'portfolio_project_images_delete' slug=project_slug pk=image.pk %}" class="purple-text">Remove image</a>
                  </div>
                </div>
              </div>
              {% endfor %}

          {% else %}
            
            <h5>You have not added any images yet!</h5>

          {% endif %}

            <center>
              <a href="{% url 'portfolio_project_view' slug=project_slug %}" class="btn purple darken-2" style="margin-top: 15px;">Go Back</a>
              <a href="{% url 'portfolio_project_images_add' slug=project_slug %}" class="btn purple" style="margin-top: 15px;">Add Image</a>
            </center>

          </div>
            
        </div>

      </div>
        
    </div>

  </div>



{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_list.html
{% extends "pages/base/template.html" %}

{% load static %}

{% block head %}
  <!--Font Awesome-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link type="text/css" rel="stylesheet" href="{% static "shop/css/materialize-social.css" %}"  media="screen,projection" />
  <style>
    .project_title {
      background:rgba(0,0,0,0.5);
      padding: 0px 7px 5px 7px;
    }
    .card {
        position: relative;
        margin: .5rem 0 1rem 0;
        max-height: 540px;
        min-height: 456px;
        background-color: #fff;
        -webkit-transition: -webkit-box-shadow .25s;
        transition: -webkit-box-shadow .25s;
        transition: box-shadow .25s;
        transition: box-shadow .25s, -webkit-box-shadow .25s;
        border-radius: 2px;
    }
    .card .card-content {
        padding: 24px;
        border-radius: 0 0 2px 2px;
        min-height: 113px;
    }
  </style>
{% endblock head %}

{% block content %}

  <div class="section"></div>

  <div class="newcontainer">

  {% if perms.portfolio.manage_projects %}
    <div class="row">
      <a href="{% url 'portfolio_project_add' %}" class="btn purple" style="margin-left: 10px;">Add new Project</a>
    </div>
    
    <div class="divider"></div>
  {% endif %}
  
    <div class="row">
      {% for project in object_list %}
        {% include "portfolio/project_list_item.html" with project=project %}
      {% endfor %}
    </div>
    
  </div>

  <div class="section"></div>

{% endblock content %}

{% block scripts %}
  <script>
    $(document).ready(function(){
      $('.materialboxed').materialbox();
    });
  </script>
{% endblock scripts %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_list_item.html
{% load static %}

<style>

.project-title {
    visibility: hidden;
    opacity: 0;
    transition: visibility 0s, opacity 0.3s linear;
}

.project-card:hover .project-title {
    visibility: visible;
    opacity: 1;
}

</style>

<div class="col xl4 l6 s12">
  <div class="card">
    <div class="card-image project-card">
      <a href="{% url 'portfolio_project_view' slug=project.slug %}"><img height="275" src="{{ project.thumbnail.url }}" alt="{{ project.title }}">
      <span class="card-title project-title"><span class="project_title"><b>{{ project.title }}</b></span></span></a>
    </div>
    <div class="card-content" style="padding-bottom: 0px; word-wrap: break-word;">
      <p>{{ project.description|truncatewords:27 }}</p>
      <br />
    </div>
    <div class="card-action">
      <div class="row" style="margin-bottom: 0px;">

        <div class="col s2">
          <a href="{{ project.planet_minecraft }}" class="waves-effect waves-light social-icon btn green darken-1 tooltipped" data-position="right" data-tooltip="See on Planet Minecraft" target="_blank">
          <i class="fas fa-globe-americas"></i></a>
        </div>        
          
        <div class="col s10">
          <div class="right">
            <a class="waves-effect waves-light social-icon btn facebook" style="margin-right: 5px;">
            <i class="fab fa-facebook-f"></i></a>

            <a class="waves-effect waves-light social-icon btn twitter" style="margin-right: 5px;">
            <i class="fab fa-twitter"></i></a>

            <a class="waves-effect waves-light social-icon btn google" style="margin-right: 5px;">
            <i class="fab fa-google-plus-g"></i></a>

            <a class="waves-effect waves-light social-icon btn pinterest">
            <i class="fab fa-pinterest-p"></i></a>
          </div>
        </div>

      </div>

      {% if perms.portfolio.manage_projects %}
        <br>
        <div class="divider"></div>
        <br>
        <div class="row" style="margin-bottom: 0px;">
          <div class="left" style="margin-left: 10px;">
            <a href="{% url 'portfolio_project_update' slug=project.slug %}" class="btn green darken-2">Update Project</a>
          </div>
          <div class="right" style="margin-right: 10px;">
            <a href="{% url 'portfolio_project_delete' slug=project.slug %}" class="btn red darken-2">Delete Project</a>
          </div>
        </div>
      {% endif %}
      

    </div>
  </div>
</div>

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_single.html
{% extends 'pages/base/template.html' %} 

{% load static %}
{% block head %}
  <link type="text/css" rel="stylesheet" href="{% static "shop/css/materialize-social.css" %}"  media="screen,projection" />
  <link type="text/css" rel="stylesheet" href="{% static "shop/css/product_single.css" %}"  media="screen,projection" />
{% endblock head %} 

{% block content %}

	<div class="newcontainer">

	  <div class="section">
	    <div class="row" style="margin-bottom: 10px;">
	      <div class="col l8 m12 s12">
	          {% include "portfolio/project_single_carousel.html" with head=head %}
	      </div>
	      <div class="col l4 m12 s12">
	      		{% include "portfolio/project_single_info.html" %}
	      </div>
	    </div>
        
        <div class="row" style="margin: 0px 0px 5px 0px;">
          <div class="col l8 m12 s12">
              <div class="section center" style="padding: 0px;">
                  <h5 style="margin: 0px; font-weight: 600;">{{ project.title }}</h5>
              </div>
          </div>
        </div>
        
	    <div class="row">
	    	<div class="col l8 m12 s12">
	          
						<div class="card purple darken-2">
			        <div class="card-content white-text">
			          <span class="card-title">Project description</span>
			          <p>{{ project.description }}</p>
			        </div>

			      </div>

	      </div>
	    </div>
	  </div>
	</div>

	{# TODO: Other creations by the Author #}

{% endblock content %} 

{% block scripts %}
    <script type="text/javascript" src="{% static "shop/js/product_single.js" %}"></script>
{% endblock scripts %}

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_single_carousel.html
{% load static %}

<div class="carousel carousel-slider center " data-indicators="true">
    {% if project.images.count > 0 %}
        <div class="carousel-fixed-item center middle-indicator">
            <div class="left">
                <a href="#" class="movePrevCarousel middle-indicator-text waves-effect waves-light content-indicator"><i class="material-icons left  middle-indicator-text">chevron_left</i></a>
            </div>
            <div class="right">
                <a href="#" class="moveNextCarousel middle-indicator-text waves-effect waves-light content-indicator"><i class="material-icons right middle-indicator-text">chevron_right</i></a>
            </div>
        </div>
    {% endif %}
        
    <div class="carousel-item" href="#one!">
        <img src="{{ project.thumbnail.url }}" alt="{{ project.title }}">
    </div>
    {% for image in project.images.all %}
        <div class="carousel-item" href="#two!">
            <img src="{{ image.image.url }}" alt="{{ project.title }}">
        </div>
    {% endfor %}
    
</div>

PHPStorm/teamvisionary-website/visionary_web/templates/portfolio/project_single_info.html
<div class="card" style="margin-top: 0px;">
    <div class="card-content black-text">
      
			<div class="row" style="margin: 0px;">
				<div class="col s6">
					<div class="left">
							<span>Author:</span>
					</div>
				</div>
				<div class="col s6">
					<div class="right">
							<span>{{ project.author }}</span>
					</div>
				</div>
			</div>
            
    </div>
</div>
<div class="card">
    <div class="card-content black-text">
        <span class="card-title">Share this map:</span>

       	<a class="waves-effect waves-light btn-floating btn-large social facebook" style="margin-right: 5px;">
				<i class="fab fa-facebook-f"></i></a>

				<a class="waves-effect waves-light btn-floating btn-large social twitter" style="margin-right: 5px;">
				<i class="fab fa-twitter"></i></a>

				<a class="waves-effect waves-light btn-floating btn-large social linkedin" style="margin-right: 5px;">
				<i class="fab fa-linkedin-in"></i></a>

				<a class="waves-effect waves-light btn-floating btn-large social google" style="margin-right: 5px;">
				<i class="fab fa-google-plus-g"></i></a>

				<a class="waves-effect waves-light btn-floating btn-large social pinterest">
				<i class="fab fa-pinterest-p"></i></a>

		</div>
</div>

{% if perms.portfolio.manage_projects %}
    <div class="card-panel">
        <a href="{% url 'portfolio_project_update' slug=project.slug %}" class="btn green darken-2" style="margin-bottom: 5px;">Update Info</a>
        <a href="{% url 'portfolio_project_images_view' slug=project.slug %}" class="btn purple darken-1" style="margin-bottom: 5px;">Manage Images</a>
        <a href="{% url 'portfolio_project_delete' slug=project.slug %}" class="btn red darken-4" style="margin-bottom: 5px;">Delete Project</a>
    </div>
{% endif %}