PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/profiles/urls.py
from django.urls import path
from .views import (UserProfileView,
                    UserProfileUpdateView,
                    UserUpdateView,
                    UserProfileAvatarUpdateView,
                    PublicProfileView)


urlpatterns = [
    path('public/<str:username>/', PublicProfileView.as_view(), name="account_public_profile"),
    path('profile/', UserProfileView.as_view(), name='account_profile'),
    path('profile/edit/info/', UserProfileUpdateView.as_view(), name='account_profile_edit_info'),
    path('profile/edit/personal/', UserUpdateView.as_view(), name='account_profile_edit_personal'),
    path('profile/edit/avatar/', UserProfileAvatarUpdateView.as_view(), name='account_profile_edit_avatar')
]

PHPStorm/teamvisionary-website/visionary_web/visionary_web/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
# from django.views.generic.base import RedirectView

from .sitemaps import StaticSitemap, PortfolioProjectSitemap


sitemaps = {
    'pages': StaticSitemap,
    'projects': PortfolioProjectSitemap,
}


urlpatterns = [
    path('', include('visionary_web.apps.pages.urls')),
    # path('dashboard/', TemplateView.as_view(template_name="dashboard/dashboard.html"), name='dashboard'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    # path('account/change_password/', TemplateView.as_view(template_name="accounts/change_password.html")),
    # path('account/forgot_password/', TemplateView.as_view(template_name="accounts/forgot_password.html")),
    # path('account/profile/', TemplateView.as_view(template_name="shop/account_profile.html")),
    # path('account/profile/edit/', TemplateView.as_view(template_name="shop/account_profile_edit.html")),
    # path('account/orders/', TemplateView.as_view(template_name="profiles/orders.html")),
    # path('account/offers/', TemplateView.as_view(template_name="profiles/offers.html")),
    # path('account/offers/edit/', TemplateView.as_view(template_name="shop/account_offers_edit.html")),
    # path('login/', TemplateView.as_view(template_name="accounts/login.html"), name='login'),
    # path('signup/', TemplateView.as_view(template_name="accounts/signup.html"), name='signup'),
    # TODO: CHECK THIS AND FIX IT
    # path('team/', TemplateView.as_view(template_name="pages/team.html"), name='team'),
    path('portfolio/', include('visionary_web.apps.portfolio.urls')),
    path('404/', TemplateView.as_view(template_name="pages/404.html"), name='404'),
    path('500/', TemplateView.as_view(template_name="pages/500.html"), name='500'),
    path('account/', include('visionary_web.apps.profiles.urls')),
    path('marketplace/', include('visionary_web.apps.marketplace.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    path('google68765b21417bb6ac.html', TemplateView.as_view(template_name="google68765b21417bb6ac.html", content_type="text/plain"), name="google_site_verification"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="sitemap"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/profiles/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from PIL import Image


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    paypal_address = models.EmailField(null=True, blank=True)  # TODO: Make this an E-mail field maybe?
    avatar = models.ImageField(upload_to="avatars/", null=True, blank=True)

    about = models.TextField(blank=True)
    country = models.CharField(max_length=50, blank=True)
    timezone = models.CharField(max_length=50, blank=True)

    facebook = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    youtube = models.URLField(blank=True)
    planet_minecraft = models.URLField(blank=True)

    def save(self, **kwargs):
        super(UserProfile, self).save()
        if self.avatar and hasattr(self.avatar, 'file'):
            image = Image.open(self.avatar)
            resized_avatar = image.resize((250, 250))
            resized_avatar.save(self.avatar.path)


@receiver(post_save, sender=User)
def post_save_userprofile(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/profiles/forms.py
from django.forms import ModelForm

from django.contrib.auth.models import User
from .models import UserProfile


class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class UserProfileForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = ('paypal_address')

PHPStorm/teamvisionary-website/visionary_web/visionary_web/apps/profiles/views.py
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
# from django.urls import reverse
# from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.shortcuts import render, get_object_or_404

# from django.http import HttpResponse

# from .forms import UserProfileForm, UserForm
from .models import UserProfile

from visionary_web.apps.marketplace.views.mixins import MarketplacePermissionMixin


class UserProfileView(LoginRequiredMixin, DetailView):
    template_name = 'profiles/account.html'

    def get_object(self):
        return get_object_or_404(UserProfile, user=self.request.user)


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'profiles/profile_edit.html'
    model = User
    fields = ['first_name', 'last_name']
    success_url = '/profiles/my_profile/'
    success_message = 'Your profile was updated successfully!'

    def get_object(self):
        return self.request.user


class UserProfileUpdateView(LoginRequiredMixin, MarketplacePermissionMixin, SuccessMessageMixin, UpdateView):
    template_name = 'profiles/profile_edit.html'
    model = UserProfile
    fields = ['paypal_address']
    success_url = '/profiles/my_profile/'
    success_message = 'Your profile was updated successfully!'

    # def form_valid(self, form):
    #     print(form.instance.server)
    #     return super(UserProfileUpdateView, self).form_valid(form)

    def get_object(self):
        return UserProfile.objects.get(user=self.request.user)


class UserProfileAvatarUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'profiles/profile_avatar_update.html'
    model = UserProfile
    fields = ['avatar']
    success_url = '/account/profile/'
    success_message = 'Your avatar was updated successfully!'

    def get_object(self):
        return UserProfile.objects.get(user=self.request.user)


class PublicProfileView(DetailView):
    template_name = 'profiles/public_profile.html'
    model = UserProfile

    def get_object(self):
        return get_object_or_404(UserProfile, user__username=self.kwargs['username'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # try:
        #     marketplace_user = MarketplaceUser.objects.get(user=self.object.user)
        # except MarketplaceUser.DoesNotExist:
        #     marketplace_user = None

        # if marketplace_user is not None:
        #     context["profile_user_is_marketplace_user"] = True
        # else:
        #     context["profile_user_is_marketplace_user"] = False

        # print(context["profile_user_is_marketplace_user"])

        # try:
        #     marketplace_manager = MarketplaceManager.objects.get(user=self.request.user)
        # except MarketplaceManager.DoesNotExist:
        #     marketplace_manager = None

        # if marketplace_manager is not None:
        #     context["request_user_is_marketplace_manager"] = True
        # else:
        #     context["request_user_is_marketplace_manager"] = False

        # print(context["request_user_is_marketplace_manager"])

        return context

PHPStorm/teamvisionary-website/visionary_web/templates/profiles/account.html
{% extends "marketplace/base/template.html" %}

{% block content %}
  
  <div class="row" style="display: flex; flex-wrap: wrap;">
    
    <div class="col l4 s12">
      <div class="card-panel">
        <div align="center">
          <p style="font-weight: 500; font-size: 20px; margin: 0px 0px 10px 0px;">{{ user.username }}</p>
          <img src="{% if user.userprofile.avatar %} {{ user.userprofile.avatar.url }} {% else %} https://placehold.it/150 {% endif %}" height="150px" width="150px" class="responsive-img circle" alt="">
          <p style="margin: 5px 0px 0px 0px;"><a href="{% url 'account_profile_edit_avatar' %}" class="purple-text">Change avatar</a></p>
        </div>
        <div>
          <p style="margin-bottom: 5px;">Settings</p>
          <div class="divider"></div>
          <p style="margin-left: 15px;"><a href="{% url 'account_change_password' %}" class="purple-text">Change password</a></p>
          <p style="margin-left: 15px;"><a href="{% url 'account_email' %}" class="purple-text">Manage e-mails</a></p>
          <p style="margin-left: 15px;"><a href="#" class="purple-text">Change personal info</a></p>
          <p style="margin-left: 15px;"><a href="#" class="purple-text">Change social links</a></p>
          <p style="margin-left: 15px;"><a href="{% url 'account_logout' %}" class="purple-text">Sign out</a></p>
        </div>
      </div>
    </div>

    <div class="col l8 s12">
      {% block account_content %}
      <div class="row" style="margin-bottom: 0px;">
        <div class="col s12">
          <ul class="collection z-depth-1">
            <li class="collection-item">
              <div>Primary e-mail
                <span class="secondary-content purple-text text-darken-4">
                  {% if user.email %}
                    {{ user.email }}
                  {% else %}
                    -
                  {% endif %}
                </span>
              </div>
            </li>
            <li class="collection-item">
              <div>First name
                <span class="secondary-content purple-text text-darken-4">
                  {% if user.first_name %}
                    {{ user.first_name }}
                  {% else %}
                    -
                  {% endif %}
                </span>
              </div>
            </li>
            <li class="collection-item">
              <div>Last name
                <span class="secondary-content purple-text text-darken-4">
                  {% if user.first_name %}
                    {{ user.last_name }}
                  {% else %}
                    -
                  {% endif %}
                </span>
              </div>
            </li>
            <li class="collection-item">
              <div>Country
                <span class="secondary-content purple-text text-darken-4">-</span>
              </div>
            </li>
            <li class="collection-item">
              <div>Timezone
                <span class="secondary-content purple-text text-darken-4">-</span>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="row" style="margin-bottom: 0px;">
        <div class="col s12">
          <ul class="collection z-depth-1">
            <li class="collection-item">
              <div>Facebook
                <span class="secondary-content purple-text text-darken-4">-</span>
              </div>
            </li>
            <li class="collection-item">
              <div>Twitter
                <span class="secondary-content purple-text text-darken-4">-</span>
              </div>
            </li>
            <li class="collection-item">
              <div>Youtube
                <span class="secondary-content purple-text text-darken-4">-</span>
              </div>
            </li>
            <li class="collection-item">
              <div>Planet Minecraft
                <span class="secondary-content purple-text text-darken-4">-</span>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="row" style="margin-bottom: 0px;">
        <div class="col s12">
          <div class="card-panel">
            <p><span style="font-weight: 500;">About me</span></p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <ul class="collection z-depth-1">
            <li class="collection-item">
              <div>Member since
                <span class="secondary-content purple-text text-darken-4">{{ user.date_joined }}</span>
              </div>
            </li>
            <li class="collection-item">
              <div>Last login
                <span class="secondary-content purple-text text-darken-4 500weight">{{ user.last_login }}</span>
              </div>
            </li>
          </ul>
        </div>
      </div>
    {% endblock account_content %}
    </div>

  </div>

{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/profiles/profile.html
{% extends "pages/base/template.html" %}

{% load static %}

{% block content %}

	<div class="section"></div>

	<div class="newcontainer">
		
		<div class="section row">

			<div class="col xl6 l6 s12">
				<div class="card">
	        <div class="card-content">

						<div class="row" style="margin-bottom: 0px;">
							<div class="col s6">
								{% if user.userprofile.avatar %}
									<img class="responsive-img"  src={{user.userprofile.avatar.url}}>
								{% else %}
									<img class="responsive-img"  src={% static "profiles/default_avatar.png" %}>
								{% endif %}
							</div>
							<div class="col s6">
								<h3 style="margin: 0px;"><div class="right">{{ user.username }}</div></h3>
							</div>
						</div>

					</div>
					<div class="card-action">
						<a href="{% url 'my_profile_edit_avatar' %}" class="purple-text">Upload new avatar</a>
					</div>
				</div>
			</div>

			<div class="col xl6 l6 s12">
				<div class="card">
					<div class="card-content">

						<div class="row" style="margin: 0px;">
							<div class="col s6">
								<div class="left">
										<span>Member since:</span>
								</div>
							</div>
							<div class="col s6">
								<div class="right">
										<span><b>{{ user.date_joined }}</b></span>
								</div>
							</div>
						</div>
						
						<div class="divider"></div>
						<br>

						<div class="row" style="margin: 0px;">
							<div class="col s6">
								<div class="left">
										<span>Last login:</span>
								</div>
							</div>
							<div class="col s6">
								<div class="right">
										<span><b>{{ user.last_login }}</b></span>
								</div>
							</div>
						</div>

						<div class="divider"></div>
						<br>

						<div class="row" style="margin: 0px;">
							<div class="col s6">
								<div class="left">
										<span>First name:</span>
								</div>
							</div>
							<div class="col s6">
								<div class="right">
									{% if user.first_name %}
										<span><b>{{ user.first_name }}</b></span>
									{% else %}
										<span><b>-</b></span>
									{% endif %}
								</div>
							</div>
						</div>
						<div class="divider"></div>
						<br>

						<div class="row" style="margin: 0px;">
							<div class="col s6">
								<div class="left">
										<span>Last name:</span>
								</div>
							</div>
							<div class="col s6">
								<div class="right">
									{% if user.last_name %}
										<span><b>{{ user.last_name }}</b></span>
									{% else %}
										<span><b>-</b></span>
									{% endif %}
								</div>
							</div>
						</div>
						<div class="divider" style="margin-bottom: 10px;"></div>
					
					</div>

					<div class="card-action">
						<a href="{% url 'my_profile_edit_personal' %}" class="purple-text">Edit Info</a>
					</div>

				</div>

			</div>

		</div>


		{% if user.marketplace_user %}
			<div class="row">
	
				<div class="col xl6 l6 s12">
					<div class="card">
						<div class="card-content">

							<div class="row" style="margin: 0px;">
								<div class="col s6">
									<div class="left">
											<span>Paypal:</span>
									</div>
								</div>
								<div class="col s6">
									<div class="right">
										{% if userprofile.paypal_address %}
											<span><b>{{ userprofile.paypal_address }}</b></span>
										{% else %}
											<span><b>-</b></span>
										{% endif %}
									</div>
								</div>
							</div>
							<div class="divider"></div>
						</div>
						<div class="card-action">
							<a href="{% url 'my_profile_edit_info' %}" class="purple-text">Manage Paypal Address</a>
						</div>
					</div>
				</div>

			</div>
		{% endif %}

		
<!--
			<div class="col xl6 l6 s12">
				<div class="card">
					<div class="card-content">
						<div class="row" style="margin: 0px;">
							<div class="col s6">
								<div class="left">
									{# TODO: Maybe show the list with all e-mails #}
										<span>Primary E-Mail:</span>
								</div>
							</div>
							<div class="col s6">
								<div class="right">
									{% if user.email %}
										<span><b>{{ user.email }}</b></span>
									{% else %}
										<span><b>-</b></span>
									{% endif %}
								</div>
							</div>
						</div>
						<div class="divider"></div>
					</div>
					<div class="card-action">
						<a href="{% url 'account_email' %}" class="purple-text">Manage E-mails</a>
					</div>
				</div>
			</div>
-->
		

	</div>


{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/profiles/profile_avatar_update.html
{% extends "profiles/account.html" %}

{% block account_content %}

<div class="section" style="padding: .30rem .75rem 1rem 0rem;">
  <span>
    <a href="{% url 'account_profile' %}" class="grey-text text-darken-2">Account</a> > Change avatar
  </span>
</div>

<div class="row">

  <div class="col s12">
    <div class="card-panel" style="padding: 25px 80px 25px 80px;">

      <p>Recommended image size is 250x250 pixels.</p>

      <form enctype="multipart/form-data" method="post">
      
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class='row'>
          <div class='file-field input-field col s12'>
            <div class="btn purple">
              <span>Select Image</span>
              <input type="file" name="avatar" required id="id_avatar">
            </div>
            <div class="file-path-wrapper">
              <input type="text" class="file-path" placeholder="{% if form.avatar.value %}{{ form.avatar.value }}{% else %}Choose a file{% endif %}">
            </div>
          </div>
          
          {% for error in form.avatar.errors %}
            <span class="left red-text" >* {{ error }}</span>
          {% endfor %}
        </div>

        <div class='row'>
          <a href="{% url 'account_profile' %}" name='btn_login' class='col s3 btn btn-large waves-effect grey darken-1'>Cancel</a>
          <button type='submit' name='btn_login' class='col s8 offset-s1 btn btn-large waves-effect purple darken-1'>Update Avatar</button>
        </div>

      </form>

    </div>
  </div>
    
</div>


{% endblock account_content %}

PHPStorm/teamvisionary-website/visionary_web/templates/profiles/profile_edit.html
{% extends "pages/base/template.html" %}

{% load static %}

{% block content %}

	<div class="section"></div>

	<div class="newcontainer">
		
		<div class="section row">

			<div class="col xl8 offset-xl2 s12">
		    <div class="card-panel" style="padding: 25px 80px 25px 80px;">

		    	<form method="post">

		    		{% csrf_token %}
		        <div class="section"></div>

						{{ form.non_field_errors }}

						{% for field in form %}
							<div class='row'>
			          <div class='input-field col s12'>
			          	{{ field }}
			            <label for='{{ field.id_for_label }}'>{{ field.label }}</label>
			          </div>
			          {% for error in field.errors %}
			          	<span class="left red-text" >* {{ error }}</span>
			          {% endfor %}
			        </div>
						{% endfor %}

		        <br />
		        <center>
		          <div class='row'>
		            <a href="{% url 'my_profile' %}" name='btn_login' class='col s3 btn btn-large waves-effect grey darken-2'>Cancel</a>
		            <button type='submit' name='btn_login' class='col s8 offset-s1 btn btn-large waves-effect purple darken-1'>Save Changes</button>
		          </div>
		        </center>
		      </form>
		    </div>

		  </div>
				
		</div>

	</div>



{% endblock content %}

PHPStorm/teamvisionary-website/visionary_web/templates/profiles/public_profile.html
{% extends "pages/base/template.html" %}

{% load static %}

{% block content %}

  <div class="section"></div>

  <div class="newcontainer">
    
    {% if request_user_is_marketplace_manager %}
      <style>
        .manager_button{
          margin-left: 15px;
        }
      </style>

      {% if profile_user_is_marketplace_user %}
        <a href="#" class="btn purple darken-2 manager_button" disabled>Grant user Marketplace Rights</a>
        <a href="{% url 'marketplace_users_remove' username=userprofile.user.username %}" class="btn purple darken-2 manager_button">Remove Marketplace Rights from User</a>
      {% else %}
        <form method="post" action="{% url 'marketplace_users_add' username=userprofile.user.username %}" style="display: inline;">{% csrf_token %}
          <button type="submit" class='btn purple darken-2 manager_button'>Grant user Marketplace Rights</button>
        </form>
        <a href="#" class="btn purple darken-2 manager_button" disabled>Remove Marketplace Rights from User</a>
      {% endif %}
    {% endif %}

    <div class="section row">

      <div class="col xl6 l6 s12">
        <div class="card">
          <div class="card-content">

            <div class="row" style="margin-bottom: 0px;">
              <div class="col s6">
                {% if user.userprofile.avatar %}
                  <img class="responsive-img"  src={{user.userprofile.avatar.url}}>
                {% else %}
                  <img class="responsive-img"  src={% static "profiles/default_avatar.png" %}>
                {% endif %}
              </div>
              <div class="col s6">
                <h3 style="margin: 0px;"><div class="right">{{ userprofile.user.username }}</div></h3>
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="col xl6 l6 s12">
        <div class="card">
          <div class="card-content">

            <div class="row" style="margin: 0px;">
              <div class="col s6">
                <div class="left">
                    <span>Member since:</span>
                </div>
              </div>
              <div class="col s6">
                <div class="right">
                    <span><b>{{ userprofile.user.date_joined }}</b></span>
                </div>
              </div>
            </div>
            
            <div class="divider"></div>
            <br>

            <div class="row" style="margin: 0px;">
              <div class="col s6">
                <div class="left">
                    <span>Last login:</span>
                </div>
              </div>
              <div class="col s6">
                <div class="right">
                    <span><b>{{ userprofile.user.last_login }}</b></span>
                </div>
              </div>
            </div>

            <div class="divider"></div>
            <br>

            <div class="row" style="margin: 0px;">
              <div class="col s6">
                <div class="left">
                    <span>First name:</span>
                </div>
              </div>
              <div class="col s6">
                <div class="right">
                  {% if userprofile.user.first_name %}
                    <span><b>{{ userprofile.user.first_name }}</b></span>
                  {% else %}
                    <span><b>-</b></span>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="divider"></div>
            <br>

            <div class="row" style="margin: 0px;">
              <div class="col s6">
                <div class="left">
                    <span>Last name:</span>
                </div>
              </div>
              <div class="col s6">
                <div class="right">
                  {% if userprofile.user.last_name %}
                    <span><b>{{ userprofile.user.last_name }}</b></span>
                  {% else %}
                    <span><b>-</b></span>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="divider" style="margin-bottom: 10px;"></div>
          
          </div>

        </div>

      </div>

    </div>



  </div>


{% endblock content %}